# Welcome to Jekyll!
#
# This config file is meant for settings that affect your entire site, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# `jekyll serve`. If you change this file, please restart the server process.

# Theme Settings
#
# Review documentation to determine if you should use `theme` or `remote_theme`
# https://mmistakes.github.io/minimal-mistakes/docs/quick-start-guide/#installing-the-theme

# theme                  : "minimal-mistakes-jekyll"
remote_theme           : "mmistakes/minimal-mistakes"
minimal_mistakes_skin    : "default" # "air", "aqua", "contrast", "dark", "dirt", "neon", "mint", "plum", "sunrise", "catppuccin_latte", "catppuccin_mocha"

# Site Settings
locale                   : "en-US"
direction                : # "ltr" (default), "rtl" # set the direction of the page
title                    :  "Angela Dawn Craig | Data Engineering Portfolio"
title_separator          : "-"
subtitle                 : "The important thing is not to stop questioning. Curiosity has its own reason for existing."
name                     : "Angela Dawn Craig"
description              : "Junior Data Engineer"
url                      : "https://spacedragon95.github.io"
baseurl                  : ""
repository               : "SpaceDragon95/SpaceDragon95.github.io"
teaser                   : # path of fallback teaser image, e.g. "/assets/images/500x300.png"
logo                     : # path of logo image to display in the masthead, e.g. "/assets/images/88x88.png"
masthead_title           : "Angela Dawn Craig"
breadcrumbs              : # true, false (default)
words_per_minute         : 200
enable_copy_code_button  : True
copyright                : "Angela Dawn Craig"
copyright_url            : # "copyright" URL, defaults to site.url
comments:
  provider               : false
atom_feed:
  hide: true

search: false
og_image                 : "/assets/images/Portfolio-Cover.png"
og_image_alt             : "Angela Dawn Craig's data engineering portfolio"

social:
  type                   : Person
  name                   : "Angela Dawn Craig"
  links:
    - "https://github.com/SpaceDragon95"
    - "https://www.linkedin.com/in/angela-dawn-craig-q1w2e3r4/"

analytics:
  provider               : false

# Site Author
author:
  name             : "Angela Dawn Craig"
  avatar           : # path of avatar image, e.g. "/assets/images/bio-photo.jpg"
  bio              : "Building ETL pipelines, data cleaning workflows, and analytical datasets using Python, SQL, PostgreSQL, Databricks, and Power BI."
  location         : "West Virginia, US"
  email            :
  # fediverse      : "@you@instance.social"  # used for fediverse:creator meta tag
  links:
    - label: "Email"
      icon: "fas fa-fw fa-square-envelope"
# Site Footer
footer:
  links:
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/SpaceDragon95"

    - label: "LinkedIn"
      icon: "fab fa-fw fa-linkedin"
      url: "https://www.linkedin.com/in/angela-dawn-craig-q1w2e3r4/"

    - label: "Email"
      icon: "fas fa-fw fa-square-envelope"
      url: "mailto:angeladawncraig.tech@gmail.com"

  since: "2026"


# Reading Files
include:
  - .htaccess
  - _pages
exclude:
  - "*.sublime-project"
  - "*.sublime-workspace"
  - vendor
  - .asset-cache
  - .bundle
  - .jekyll-assets-cache
  - .sass-cache
  - assets/js/plugins
  - assets/js/_main.js
  - assets/js/vendor
  - Capfile
  - CHANGELOG
  - config
  - Gemfile
  - Gemfile.lock
  - Gruntfile.js
  - gulpfile.js
  - LICENSE
  - log
  - minimal-mistakes-jekyll.gemspec
  - node_modules
  - package.json
  - package-lock.json
  - Rakefile
  - README.md
  - tmp
  - /docs # ignore Minimal Mistakes /docs
  - /test # ignore Minimal Mistakes /test
keep_files:
  - .git
  - .svn
encoding: "utf-8"
markdown_ext: "markdown,mkdown,mkdn,mkd,md"

# Conversion
markdown: kramdown
highlighter: rouge
lsi: false
excerpt_separator: "\n\n"
incremental: false


# Markdown Processing
kramdown:
  input: GFM
  hard_wrap: false
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  smart_quotes: lsquo,rsquo,ldquo,rdquo
  enable_coderay: false


# Sass/SCSS
sass:
  sass_dir: _sass
  style: compressed
  quiet_deps: true
  silence_deprecations: ['import']


# Outputting
permalink: /:categories/:title/
timezone:

# Plugins
plugins:
  - jekyll-sitemap
  - jekyll-include-cache

# Allowed plugins when building in safe mode
whitelist:
  - jekyll-sitemap
  - jekyll-include-cache

# HTML Compression
# - https://jch.penibelst.de/
compress_html:
  clippings: all
  ignore:
    envs: development
